spring:
  cache:
    redis:
      time-to-live: 12h

resilience4j:
  ratelimiter:
    instances:
      weathers:
        limit-refresh-period: 20s
        limit-for-period: 5
        timeout-duration: 2s

roadmap-weather:
  api:
    visual-crossing:
      url: https://weather.visualcrossing.com
      key: insert-your-key
